#!/usr/bin/env python3
import sys
import re
import argparse

# ---------------------------------------------------------------------
# This script computes Jain's Fairness Index based on per-writer message
# counts parsed from the output of:
#
#   parse_mdev_log.py --detail
#
# Jain's Fairness Index is a widely-used quantitative metric to evaluate
# resource-sharing fairness in operating systems and virtualization.
#
# Given n writers with throughputs (or message counts):
#   x1, x2, ..., xn
#
# Jain's Fairness Index J is defined as:
#
#                (x1 + x2 + ... + xn)^2
#   J = ------------------------------------------
#        n * (x1^2 + x2^2 + ... + xn^2)
#
# Properties:
#   - 0 < J <= 1
#   - J = 1      : perfectly fair (all xi equal)
#   - J -> 0     : extremely unfair
#
# In test4_fairness.sh:
#   xi corresponds to the number of messages produced by each VM writer
#   during the same execution window.
# ---------------------------------------------------------------------

WRITER_RE = re.compile(r'^\s+(\S+)\s+(\d+)$')

def parse_args():
    ap = argparse.ArgumentParser(
        description="Compute Jain Fairness Index from parse_mdev_log.py output"
    )
    ap.add_argument(
        "input",
        help="Input file generated by parse_mdev_log.py --detail (e.g., t4_raw.txt)"
    )
    return ap.parse_args()

def jain_index(values):
    """
    Compute Jain's Fairness Index.

    values: list of non-negative integers (or floats),
            e.g., per-writer message counts.

    Formula:
        J = (sum(values))^2 / (n * sum(values[i]^2))

    where:
        n = number of writers

    Returns:
        float in range (0, 1]
    """
    n = len(values)
    if n == 0:
        return 0.0

    s = sum(values)
    sq = sum(v * v for v in values)

    # Avoid division by zero (e.g., all writers produced 0 messages)
    if sq == 0:
        return 0.0

    return (s * s) / (n * sq)

def main():
    args = parse_args()

    writers = {}

    # Parse writer statistics from the "writers:" section
    with open(args.input) as f:
        in_writers = False
        for line in f:
            line = line.rstrip()

            if line.strip() == "writers:":
                in_writers = True
                continue

            if in_writers:
                m = WRITER_RE.match(line)
                if not m:
                    # End of writers section
                    in_writers = False
                    continue

                writer_id = m.group(1)
                count = int(m.group(2))
                writers[writer_id] = count

    if not writers:
        print("ERROR: no writer data found in input file")
        sys.exit(1)

    values = list(writers.values())
    jain = jain_index(values)

    print("==== Jain Fairness Index ====")
    print(f"writers : {len(values)}")
    for w, v in writers.items():
        print(f"  {w:10s}: {v}")

    print(f"\nJain index: {jain:.6f}")

    # Qualitative interpretation (useful for experiment reports)
    if abs(jain - 1.0) < 1e-6:
        print("fairness : PERFECT")
    elif jain >= 0.9:
        print("fairness : GOOD")
    elif jain >= 0.8:
        print("fairness : ACCEPTABLE")
    else:
        print("fairness : POOR")

if __name__ == "__main__":
    main()
